global:
  scrape_interval: 1s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: "flask-app-metrics"
    static_configs:
      - targets: ["192.168.32.137:5000"]  # Flask app URL
    metrics_path: "/metrics"
  - job_name: "prometheus-self-monitoring"
    static_configs:
      - targets: ["localhost:9090"]  # Self-monitoring Prometheus instance
